### ISSUE TITLE
Need some support for gemm!

### ISSUE THREAD

**Issue by NoelAraujo** [emmt/StructuredArrays.jl#1]
First of all, great package, I have many uses for it.

Second, I tested some LinearAlgebra examples, and notice that matrix multiplication was specially slow. My idea was to use the `gemm!` function, but I got an error about strides. Below a code to show the issue (last line), and also some extra computations for a future reader looking for example:

```
using Distances, LinearAlgebra, StructuredArrays, BenchmarkTools
function G_fnc(j,k)
    Γ = 1.0
    k₀ = norm([0,0,1])
    Δ = 0.0
    if j==k
        G = 1im * Δ - Γ / 2
    else
        R_jk = norm(r[j,:] - r[k,:])
        G = -(Γ / 2) * exp(1im * k₀ * R_jk) / (1im * k₀ * R_jk)
    end
    return G
end

N = 20
r = 500.0.*rand(N,3)

R_jk_g = Distances.pairwise(Euclidean(), r, r, dims = 1);
G_dense = zeros(ComplexF64, N, N);
@. G_dense = -(1 / 2) * exp(1im * 1 * R_jk_g) / (1im * 1 * R_jk_g);
G_dense[LinearAlgebra.diagind(G_dense)] .= 1im * 0.0 - 1 / 2;


G_new = StructuredArray(G_fnc, (N,N));

#### eigenvalues
@time a,b = eigen(G_dense);
@time aa,bb = eigen(G_new);


#### solver
yy = rand(N);
@time x1 = G_dense\yy;
@time x2 = G_new\yy;


#### mmatrix multiplication
@btime C = G_dense*G_dense;
@btime CC = G_new*G_new;

C = zeros(eltype(G_dense), N, N);

@time BLAS.gemm!('N', 'N', 1.0 + 0.0im, G_dense, G_dense, 0.0 + 0.0im, C);
@time BLAS.gemm!('N', 'N', 1.0 + 0.0im, G_new, G_new, 0.0 + 0.0im, C); ## here the issue
```

The error:
`ERROR: MethodError: no method matching strides(::StructuredArray{Complex{Float64},2,IndexCartesian,typeof(G_fnc)})`

Is there any easy solution ?

**Comment by emmt** [comment]
You cannot use a structured array in `Blas.gemm!` because `Blas.gemm!` expects an array whose coefficients are stored in memory while the purpose of a structured array is precisely to avoid storage of coefficients in memory (they are computed on the fly). In order to apply  `Blas.gemm!`, you may convert the structured array into a regular array (which will consume memory). This is as ismple as `Array(G_new)` and may be useful if the size of the array is not too big and if you use the array multiple times. In any cases, you may speed-up computations by optimizing and/or in-lining the function called to give the coefficients.  In your case, `G_fnc(j,k)` may be improved in some places:
- `k₀ = norm([0,0,1])` is a constant that should be pre-computed:
 ```julia
  k₀ = 1.0
  ```
- The computation of `R_jk` involves temporary arrays (to store `r[j,:]` and `r[k,:]`), these temporaries should be avoided or, better, precomputed. To avoid temporaries:
  ```julia
  R_jk = sqrt((r[j,1] - r[k,1])^2 + (r[j,2] - r[k,2])^2 + (r[j,3] - r[k,3])^2)
  ```
- Expressions can be simplified because `Δ = 0.0`, `Γ = 1.0` etc. 
- The variable `r` is a global variable. [That may have an impact on performances.](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables)

**Comment by NoelAraujo** [comment]
Thank you for the reply.

`You cannot use a structured array in Blas.gemm! because Blas.gemm! expects an array whose coefficients are stored in memory`
I (more or less) was expecting this from Lapack, I just had some hope that matrix multiplication could be a little faster without extra effort.

And about performance, indeed I can do something better, I was just lazy to improve my tests before open this issue.

Talking about this, how do you suggest to not use global variables ? 
What I have in mind is to define a local new function like the example below. Is this the best way to do it ??

```
using Distributed
addprocs(3)

@everywhere using LinearAlgebra, StructuredArrays
@everywhere function G_fnc_with_r(j,k,r)
    Γ = k₀ = 1.0
    Δ = 0.0
    if j==k
        G = 1im * Δ - Γ / 2
    else
        R_jk = sqrt((r[j,1] - r[k,1])^2 + (r[j,2] - r[k,2])^2 + (r[j,3] - r[k,3])^2)
        G = -(Γ / 2) * exp(1im * k₀ * R_jk) / (1im * k₀ * R_jk)
    end
    return G
end

@everywhere function to_be_run_in_pmap(N)
    N = 20
    r = 500.0.*rand(N,3)
    G_fnc(j,k) = G_fnc_with_r(j,k, r) # creates a new function everytime
    G_new = StructuredArray(G_fnc, (N,N));
    return sum(sum(G_new, dims=1)) ## doing something not import
end

pmap(to_be_run_in_pmap, 3:10)
```

**Comment by emmt** [comment]
How faster is the matrix multiplication optimized  function?

You can avoid the issues with global variables by using a closure to define the structured array. You may also avoid the uncertainty of the type of the global variable by making it a constant reference to an array of known type:

```julia
const r = Ref{Array{Float64,2}}()
```
and the use `r[] = ... ` to store the array and `r[][i,j]` to use it, or call the function `G_fnc_with_r` as `G_fnc_with_r(i,j,r[])`.

When optimizing a function, you should be aware of tools such as `@code_warntype`, or packages such as `BenchmarkTools`.

Again, if your array fits in memory you may just compute it.

Otherwise I am not an expert of parallel processing.
